POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "thalaadam14@gmail.com",
    "password": "1234"
}

###
post http://localhost:3000/api/auth/fortgotPassword
Content-Type: application/json

{
    "email": "thalaadam14@gmail.com"
}
###
post htpp://localhost:3000/api/auth/restPassword
Content-Type: application/json

{
    "otp": 11111,
    "otpToken": "",
    "newPassword": "1234567"
}