POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "hounaida",
    "email": "hounaidaalibilal057@gmail.com",
    "password": "123456"
}

###
PATCH http://localhost:3000/api/auth/verify
Content-Type: application/json

{
  "otp": 405400,
  "otpToken": "e75413b3-27b5-481f-a717-15ec23300807",
  "purpose": "verify email"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "hounaidaalibilal057@gmail.com",
    "password": "123456"
}

###
post http://localhost:3000/api/auth/fortgotPassword
Content-Type: application/json

{
    "email": "hounaidaalibilal057@gmail.com"
}
###
post http://localhost:3000/api/auth/restPassword
Content-Type: application/json

{
    "otp": 2375804,
    "otpToken": "50c98f5b-510a-49ec-927f-c2aa6c52afb0",
    "newPassword": "1234567"
}
